package tripleprice.service;

public enum LocationType {
	CONTINENT(1),
	SUB_CONTINENT(2),
	COUNTRY(3),
	ADMINISTRATION(4),
	ARCTIC_REGION(5),
	AREA(6),
	AUTONOMOUS(7),
	CANTON(8),
	CAPITAL(9),
	CHAINS_OF_ISLANDS(10),
	CITY(11),
	COMMUNE(12),
	COUNCIL_AREA(13),
	COUNTY(14),
	DEPARTMENT(15),
	DEPENDENCY(16),
	DISTRICT(17),
	DIVISION(18),
	ECONOMIC_PREFECTURE(19),
	EMIRATE(20),
	ENTITY(21),
	FEDERAL_DISTRICT(22),
	GEOGRAPHICAL_ENTITY(23),
	GOVERNORATE(24),
	GROUP_OF_ISLANDS(25),
	INDIGENOUS_REGION(26),
	ISLAND(27),
	LAND(28),
	LOCAL_COUNCIL(29),
	LONDON_BOROUGH(30),
	METROPOLITAN_CITY(31),
	MUNICIPALITY(32),
	OBLAST(33),
	OUTLYING_AREA(34),
	PAKISTAN_ADMINISTRERED_AREA(35),
	PARISH(36),
	PARTISH(37),
	POPULARATE(38),
	PREFECTURE(39),
	PROVINCE(40),
	QUARTER(41),
	RAYON(42),
	REGION(43),
	REPUBLIC(44),
	SPECIAL_CITY(45),
	STATE(46),
	TERRITORY(47),
	TOWN(48),
	UNION_TERRITORY(49),
	UNITARY_AUTHORITY(50),
	URBAN_COMMUNITY(51),
	VOIVODSHIP(52),
	WARD(53),
	ZONE(54),
	UNKNOW(55);
	
	int intValue;

	LocationType(int intValue) {
		this.intValue = intValue;
	}

	public int valueOf(int intValue) {
		return 0;
	}

}
